name: Daily Job

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-daily:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: yarn
      - run: node src/index.js
      - name: commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output
          git commit -m 'update'
          git push